package org.vstu.compprehension.services.mappers;

import org.jetbrains.annotations.NotNull;
import org.springframework.stereotype.Component;
import org.vstu.compprehension.businesslogic.Concept;
import org.vstu.compprehension.businesslogic.Law;
import org.vstu.compprehension.businesslogic.QuestionRequest;
import org.vstu.compprehension.businesslogic.Skill;
import org.vstu.compprehension.businesslogic.Tag;
import org.vstu.compprehension.data.question.QuestionRequestLogData;
import org.vstu.compprehension.mappers.Mapper;

@Component
class QuestionRequestLogMapper implements Mapper<QuestionRequest, QuestionRequestLogData> {

    @Override
    public @NotNull QuestionRequestLogData map(@NotNull QuestionRequest source) {
        return QuestionRequestLogData.builder()
                .id(source.getId())
                .exerciseAttemptId(source.getExerciseAttemptId())
                .domainShortname(source.getDomainShortname())
                .targetConceptNames(source.getTargetConcepts().stream().map(Concept::getName).toList())
                .deniedConceptNames(source.getDeniedConcepts().stream().map(Concept::getName).toList())
                .allowedConceptNames(source.getAllowedConcepts().stream().map(Concept::getName).toList())
                .targetLawNames(source.getTargetLaws().stream().map(Law::getName).toList())
                .deniedLawNames(source.getDeniedLaws().stream().map(Law::getName).toList())
                .allowedLawNames(source.getAllowedLaws().stream().map(Law::getName).toList())
                .targetSkillNames(source.getTargetSkills().stream().map(Skill::getName).toList())
                .deniedSkillNames(source.getDeniedSkills().stream().map(Skill::getName).toList())
                .allowedSkillNames(source.getAllowedSkills().stream().map(Skill::getName).toList())
                .targetTags(source.getTargetTags().stream().map(Tag::getName).toList())
                .conceptsTargetedBitmask(Concept.combineToBitmask(source.getTargetConcepts()))
                .conceptsDeniedBitmask(Concept.combineToBitmask(source.getDeniedConcepts()))
                .lawsTargetedBitmask(Law.combineToBitmask(source.getTargetLaws()))
                .lawsDeniedBitmask(Law.combineToBitmask(source.getDeniedLaws()))
                .targetTagsBitmask(Tag.combineToBitmask(source.getTargetTags()))
                .skillsTargetedBitmask(Skill.combineToBitmask(source.getTargetSkills()))
                .skillsDeniedBitmask(Skill.combineToBitmask(source.getDeniedSkills()))
                .deniedQuestionNames(source.getDeniedQuestionNames())
                .deniedQuestionTemplateIds(source.getDeniedQuestionTemplateIds())
                .deniedQuestionMetaIds(source.getDeniedQuestionMetaIds())
                .solvingDuration(source.getSolvingDuration())
                .complexity(source.getComplexity())
                .stepsMin(source.getStepsMin())
                .stepsMax(source.getStepsMax())
                .complexitySearchDirection(source.getComplexitySearchDirection())
                .lawsSearchDirection(source.getLawsSearchDirection())
                .chanceToPickAutogeneratedQuestion(source.getChanceToPickAutogeneratedQuestion())
                .build();
    }
}
