# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bkt-service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'bkt-service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62kt-service.proto\x12\x03\x62kt\"W\n\x13UpdateRosterRequest\x12\x0e\n\x06roster\x18\x01 \x01(\t\x12\x0f\n\x07student\x18\x02 \x01(\t\x12\x0f\n\x07\x63orrect\x18\x03 \x01(\x08\x12\x0e\n\x06skills\x18\x04 \x03(\t\"&\n\x14UpdateRosterResponse\x12\x0e\n\x06roster\x18\x01 \x01(\t2Q\n\nBktService\x12\x43\n\x0cUpdateRoster\x12\x18.bkt.UpdateRosterRequest\x1a\x19.bkt.UpdateRosterResponseB.\n org.vstu.compprehension.bkt.grpcB\x08\x42ktProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bkt_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n org.vstu.compprehension.bkt.grpcB\010BktProtoP\001'
  _globals['_UPDATEROSTERREQUEST']._serialized_start=26
  _globals['_UPDATEROSTERREQUEST']._serialized_end=113
  _globals['_UPDATEROSTERRESPONSE']._serialized_start=115
  _globals['_UPDATEROSTERRESPONSE']._serialized_end=153
  _globals['_BKTSERVICE']._serialized_start=155
  _globals['_BKTSERVICE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
