package org.vstu.compprehension.data.question;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.vstu.compprehension.data.enums.SearchDirections;

import java.util.List;
import java.util.UUID;

/**
 * Запрос вопроса, каким он уходит в журнал.
 * <p>
 * Строит его {@code QuestionRequest} — из понятий и законов, известных домену, остаются
 * их имена и битовые маски. Раньше он строил сразу JPA-сущность, из-за чего вся
 * бизнес-логика вопроса зависела от слоя хранения ради одного объекта-протокола.
 *
 * @param id тот же идентификатор, что у самого запроса: по нему журнал поиска в банке
 *           связывается с запросом, который его вызвал
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class QuestionRequestLogData {
    private @NotNull UUID id;
    private @Nullable Long exerciseAttemptId;
    private String domainShortname;

    private List<String> targetConceptNames;
    private List<String> deniedConceptNames;
    /** Банк вправе считать их «желательными», а не обязательными. */
    private List<String> allowedConceptNames;

    private List<String> targetLawNames;
    private List<String> deniedLawNames;
    private List<String> allowedLawNames;

    private List<String> targetSkillNames;
    private List<String> deniedSkillNames;
    private List<String> allowedSkillNames;

    private List<String> targetTags;

    private long conceptsTargetedBitmask;
    private long conceptsDeniedBitmask;
    private long lawsTargetedBitmask;
    private long lawsDeniedBitmask;
    private long skillsDeniedBitmask;
    private long skillsTargetedBitmask;
    private long targetTagsBitmask;

    private @Nullable List<String> deniedQuestionNames;
    private @Nullable List<String> deniedQuestionTemplateIds;
    /** То же, что {@link #deniedQuestionNames}, но идентификаторами. */
    private @Nullable List<Integer> deniedQuestionMetaIds;

    /** Условная единица: 1 — вопрос решается быстро, 10 — очень долго. */
    private int solvingDuration;

    /** Сложность задания в диапазоне [0..1]. */
    private float complexity;

    /** Минимум шагов в решении. */
    private int stepsMin;
    /** Максимум шагов в решении. */
    private int stepsMax;

    private SearchDirections complexitySearchDirection;
    private SearchDirections lawsSearchDirection;

    /** Вероятность выбрать сгенерированный вопрос вместо составленного вручную, [0..1]. */
    private double chanceToPickAutogeneratedQuestion;
}
