package org.vstu.compprehension.models.businesslogic.strategies;

import org.jetbrains.annotations.NotNull;
import org.springframework.beans.factory.annotation.Autowired;
import org.vstu.compprehension.models.businesslogic.QuestionRequest;
import org.vstu.compprehension.models.businesslogic.domains.DomainFactory;
import org.vstu.compprehension.models.entities.ExerciseAttemptEntity;

import org.springframework.stereotype.Component;
import javax.inject.Singleton;

/**
 * Modification of GradeConfidenceBaseStrategy that sets 50/50 probability to select manual or auto-generated question.
 */
@Component @Singleton
public class GradeConfidenceBaseStrategy_Manual50Autogen50 extends GradeConfidenceBaseStrategy {

    @Autowired
    public GradeConfidenceBaseStrategy_Manual50Autogen50(DomainFactory domainFactory) {
        super(domainFactory);
    }

    @NotNull
    @Override
    public String getStrategyId() {
        return this.getClass().getSimpleName();  // GradeConfidenceBaseStrategy_Manual50Autogen50
    }

    @Override
    public QuestionRequest generateQuestionRequest(ExerciseAttemptEntity exerciseAttempt) {
        QuestionRequest qr = super.generateQuestionRequest(exerciseAttempt);
        qr.setChanceToPickAutogeneratedQuestion(0.5);
        qr.setSolvingDuration(2);  // low duration from [1..10] range
        return qr;
    }
}
