package org.vstu.compprehension.repositories.mappers;

import org.jetbrains.annotations.NotNull;
import org.springframework.stereotype.Component;
import org.vstu.compprehension.data.question.QuestionRequestLogData;
import org.vstu.compprehension.entities.QuestionRequestLogEntity;
import org.vstu.compprehension.mappers.Mapper;

/** Журнальная запись о том, каким запросом подбирался вопрос. */
@Component
class QuestionRequestLogEntityMapper implements Mapper<QuestionRequestLogData, QuestionRequestLogEntity> {

    @Override
    public @NotNull QuestionRequestLogEntity map(@NotNull QuestionRequestLogData source) {
        return QuestionRequestLogEntity.builder()
                .id(source.getId())
                .exerciseAttemptId(source.getExerciseAttemptId())
                .domainShortname(source.getDomainShortname())
                .targetConceptNames(source.getTargetConceptNames())
                .deniedConceptNames(source.getDeniedConceptNames())
                .allowedConceptNames(source.getAllowedConceptNames())
                .targetLawNames(source.getTargetLawNames())
                .deniedLawNames(source.getDeniedLawNames())
                .allowedLawNames(source.getAllowedLawNames())
                .targetSkillNames(source.getTargetSkillNames())
                .deniedSkillNames(source.getDeniedSkillNames())
                .allowedSkillNames(source.getAllowedSkillNames())
                .targetTags(source.getTargetTags())
                .conceptsTargetedBitmask(source.getConceptsTargetedBitmask())
                .conceptsDeniedBitmask(source.getConceptsDeniedBitmask())
                .lawsTargetedBitmask(source.getLawsTargetedBitmask())
                .lawsDeniedBitmask(source.getLawsDeniedBitmask())
                .skillsDeniedBitmask(source.getSkillsDeniedBitmask())
                .skillsTargetedBitmask(source.getSkillsTargetedBitmask())
                .targetTagsBitmask(source.getTargetTagsBitmask())
                .deniedQuestionNames(source.getDeniedQuestionNames())
                .deniedQuestionTemplateIds(source.getDeniedQuestionTemplateIds())
                .deniedQuestionMetaIds(source.getDeniedQuestionMetaIds())
                .solvingDuration(source.getSolvingDuration())
                .complexity(source.getComplexity())
                .stepsMin(source.getStepsMin())
                .stepsMax(source.getStepsMax())
                .complexitySearchDirection(source.getComplexitySearchDirection())
                .lawsSearchDirection(source.getLawsSearchDirection())
                .chanceToPickAutogeneratedQuestion(source.getChanceToPickAutogeneratedQuestion())
                .build();
    }
}
