package org.vstu.compprehension.businesslogic;

import lombok.Builder;
import lombok.Value;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.vstu.compprehension.enums.SearchDirections;

import java.util.List;
import java.util.Objects;
import java.util.UUID;

@Value
public class QuestionRequest {
    @NotNull UUID id;
    @NotNull List<Concept> deniedConcepts;
    @NotNull List<Concept> targetConcepts;
    /** Question Storage can treat this as "optional targets" or "preferred" */
    @NotNull List<Concept> allowedConcepts;
    @NotNull List<Law> targetLaws;
    @NotNull List<Law> deniedLaws;
    @NotNull List<Law> allowedLaws;
    @NotNull List<Tag> targetTags;
    @NotNull List<Skill> targetSkills;
    @NotNull List<Skill> deniedSkills;
    @NotNull List<Skill> allowedSkills;

    @NotNull List<String> deniedQuestionNames;
    @NotNull List<String> deniedQuestionTemplateIds;
    @NotNull List<Integer> deniedQuestionMetaIds; // same as deniedQuestionNames but using ids instead of names

    /**
     * Условная единица, показывающая долго или быстро решается вопрос
     * 1 - быстро, 10 - очень долго
     */
    int solvingDuration;
    /**
     * Сложность задания [0..1]
     */
    float complexity;

    /** минимум шагов в решении */
    int stepsMin;
    /** максимум шагов в решении */
    int stepsMax;

    /**
     * Направление поиска по сложности
     */
    @NotNull SearchDirections complexitySearchDirection;

    /**
     * Направление поиска по сложности
     */
    @NotNull SearchDirections lawsSearchDirection;

    /**
     * Probability of choosing an auto-generated question
     * Вероятность выбора авто-сгенерированного вопроса
     * range: [0..1]
     * 0: always pick manual question
     * 1: always pick auto-generated question
     */
    double chanceToPickAutogeneratedQuestion;

    @NotNull String domainShortname;

    @Nullable Long exerciseAttemptId;

    @Builder(toBuilder = true)
    private QuestionRequest(@Nullable UUID id,
                            @Nullable List<Concept> deniedConcepts,
                            @Nullable List<Concept> targetConcepts,
                            @Nullable List<Concept> allowedConcepts,
                            @Nullable List<Law> targetLaws,
                            @Nullable List<Law> deniedLaws,
                            @Nullable List<Law> allowedLaws,
                            @Nullable List<Tag> targetTags,
                            @Nullable List<Skill> targetSkills,
                            @Nullable List<Skill> deniedSkills,
                            @Nullable List<Skill> allowedSkills,
                            @Nullable List<String> deniedQuestionNames,
                            @Nullable List<String> deniedQuestionTemplateIds,
                            @Nullable List<Integer> deniedQuestionMetaIds,
                            int solvingDuration,
                            float complexity,
                            int stepsMin,
                            int stepsMax,
                            @Nullable SearchDirections complexitySearchDirection,
                            @Nullable SearchDirections lawsSearchDirection,
                            @Nullable Double chanceToPickAutogeneratedQuestion,
                            @NotNull String domainShortname,
                            @Nullable Long exerciseAttemptId) {
        this.id = Objects.requireNonNullElseGet(id, UUID::randomUUID);
        this.deniedConcepts = copy(deniedConcepts);
        this.targetConcepts = copy(targetConcepts);
        this.allowedConcepts = copy(allowedConcepts);
        this.targetLaws = copy(targetLaws);
        this.deniedLaws = copy(deniedLaws);
        this.allowedLaws = copy(allowedLaws);
        this.targetTags = copy(targetTags);
        this.targetSkills = copy(targetSkills);
        this.deniedSkills = copy(deniedSkills);
        this.allowedSkills = copy(allowedSkills);
        this.deniedQuestionNames = copy(deniedQuestionNames);
        this.deniedQuestionTemplateIds = copy(deniedQuestionTemplateIds);
        this.deniedQuestionMetaIds = copy(deniedQuestionMetaIds);
        this.solvingDuration = solvingDuration;
        this.complexity = complexity;
        this.stepsMin = stepsMin;
        this.stepsMax = stepsMax;
        this.complexitySearchDirection = Objects.requireNonNullElse(complexitySearchDirection, SearchDirections.TO_SIMPLE);
        this.lawsSearchDirection = Objects.requireNonNullElse(lawsSearchDirection, SearchDirections.TO_SIMPLE);
        this.chanceToPickAutogeneratedQuestion = Objects.requireNonNullElse(chanceToPickAutogeneratedQuestion, 1.0);
        this.domainShortname = Objects.requireNonNull(domainShortname, "domainShortname");
        this.exerciseAttemptId = exerciseAttemptId;
    }

    private static <T> @NotNull List<T> copy(@Nullable List<T> source) {
        return source == null ? List.of() : List.copyOf(source);
    }
}
