package org.vstu.compprehension.entities;

import io.hypersistence.utils.hibernate.type.json.JsonType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.Type;
import org.vstu.compprehension.enums.SearchDirections;

import java.util.Date;
import java.util.List;
import java.util.UUID;

@Entity
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "question_request_log")
public class QuestionRequestLogEntity {
    @Id
    private UUID id;

    private Long exerciseAttemptId;

    @Column(nullable = false)
    private String domainShortname;

    @Type(JsonType.class)
    @Column(nullable = false)
    private List<String> targetConceptNames;

    @Type(JsonType.class)
    @Column(nullable = false)
    private List<String> deniedConceptNames;

    /** Question Storage can treat this as "optional targets" or "preferred" */
    @Type(JsonType.class)
    @Column(nullable = false)
    private List<String> allowedConceptNames;

    @Type(JsonType.class)
    @Column(nullable = false)
    private List<String> targetLawNames;

    @Type(JsonType.class)
    @Column(nullable = false)
    private List<String> deniedLawNames;

    @Type(JsonType.class)
    @Column(nullable = false)
    private List<String> allowedLawNames;

    @Type(JsonType.class)
    @Column(nullable = false)
    private List<String> targetSkillNames;

    @Type(JsonType.class)
    @Column(nullable = false)
    private List<String> deniedSkillNames;

    @Type(JsonType.class)
    @Column(nullable = false)
    private List<String> allowedSkillNames;


    @Type(JsonType.class)
    @Column(nullable = false)
    private List<String> targetTags;

    // bit fields
    long conceptsTargetedBitmask;  // set to 0 if traceConceptsTargetedBitmask set
    long conceptsDeniedBitmask;
    long lawsTargetedBitmask;
    long lawsDeniedBitmask;
    long skillsDeniedBitmask;
    long skillsTargetedBitmask;
    long targetTagsBitmask;

    @Type(JsonType.class)
    @Column(nullable = false)
    private List<String> deniedQuestionNames;

    @Type(JsonType.class)
    @Column(nullable = false)
    private List<String> deniedQuestionTemplateIds;
    
    @Type(JsonType.class)
    @Column(nullable = false)
    private List<Integer> deniedQuestionMetaIds;  // same as deniedQuestionNames but using ids instead of names

    /**
     * Условная единица, показывающая долго или быстро решается вопрос
     * 1 - быстро, 10 - очень долго
     */
    @Column(nullable = false)
    private int solvingDuration;


    /**
     * Сложность задания [0..1]
     */
    @Column(nullable = false)
    private float complexity;

    /** минимум шагов в решении */
    private int stepsMin;
    /** максимум шагов в решении */
    private int stepsMax;

    /**
     * Направление поиска по сложности
     */
    @Enumerated(EnumType.ORDINAL)
    @Column(nullable = false)
    private SearchDirections complexitySearchDirection;

    /**
     * Направление поиска по сложности
     */
    @Enumerated(EnumType.ORDINAL)
    @Column(nullable = false)
    private SearchDirections lawsSearchDirection;

    /**
     * Probability of choosing an auto-generated question
     * Вероятность выбора авто-сгенерированного вопроса
     * range: [0..1]
     * 0: always pick manual question
     * 1: always pick auto-generated question
     */
    @ColumnDefault("1")
    @Column(nullable = false)
    private double chanceToPickAutogeneratedQuestion = 1;
    
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Date createdAt;
}
